# Generated by Django 4.1.2 on 2022-10-29 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followers',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='followers',
            name='object',
        ),
        migrations.AddField(
            model_name='followers',
            name='followed',
            field=models.CharField(default='followed', max_length=50),
        ),
        migrations.AddField(
            model_name='followers',
            name='follower',
            field=models.CharField(default='follower', max_length=50),
        ),
        migrations.CreateModel(
            name='FollowRequest',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('type', models.CharField(default='Follow', max_length=50)),
                ('summary', models.CharField(default='You have a follow request', max_length=500)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor', to=settings.AUTH_USER_MODEL)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
