# Generated by Django 4.1.2 on 2022-10-20 18:11

import api.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=api.user.models.generate_id, max_length=128, primary_key=True, serialize=False),
        ),
    ]
