# Generated by Django 4.1.2 on 2022-10-31 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbox',
            name='author',
        ),
        migrations.DeleteModel(
            name='FollowRequest',
        ),
        migrations.DeleteModel(
            name='Inbox',
        ),
    ]
