# Generated by Django 4.1.2 on 2022-10-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='url',
            field=models.CharField(default='http://127.0.0.1:8000/authors/b402ebe6350aa9f4f1fb82c5c358d1430fa3fcb5017b1bb144f9b2000caf812c', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='b402ebe6350aa9f4f1fb82c5c358d1430fa3fcb5017b1bb144f9b2000caf812c', max_length=128, primary_key=True, serialize=False),
        ),
    ]
