# Generated by Django 4.1.2 on 2022-10-29 23:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0003_alter_followers_followed_alter_followers_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='followrequest',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
