# Generated by Django 4.1.2 on 2022-10-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0003_user_url_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='afea8aa4b4afe424a6600c532d517d13a422e0cc46ba5a392f929000a6ccc592', max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='url',
            field=models.CharField(default='http://127.0.0.1:8000/authors/afea8aa4b4afe424a6600c532d517d13a422e0cc46ba5a392f929000a6ccc592', max_length=255),
        ),
    ]
