# Generated by Django 4.1.2 on 2022-10-27 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0004_followrequest_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followers',
            name='type',
        ),
    ]
