# Generated by Django 4.1.2 on 2022-10-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0004_alter_user_id_alter_user_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='a247db9f3bd26bc873f89c650790d469be1ade7c4dcb10047b1b6b42c2840e95', max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='url',
            field=models.CharField(default='http://127.0.0.1:8000/authors/a247db9f3bd26bc873f89c650790d469be1ade7c4dcb10047b1b6b42c2840e95', max_length=255),
        ),
    ]
