# Generated by Django 4.1.2 on 2022-10-27 01:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0005_remove_followers_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='followers',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
