# Generated by Django 4.1.2 on 2022-10-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0006_alter_user_id_alter_user_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AddField(
            model_name='user',
            name='github',
            field=models.URLField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='host',
            field=models.CharField(default='http://127.0.0.1:8000/', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(default='author', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='93d329e931c6de144c4307bc0acd95bd7780e79179a74a9213e1eb23eaa66654', max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='url',
            field=models.CharField(default='http://127.0.0.1:8000/authors/93d329e931c6de144c4307bc0acd95bd7780e79179a74a9213e1eb23eaa66654', max_length=255),
        ),
    ]
