# Generated by Django 4.1.2 on 2022-10-27 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0006_followers_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followers',
            name='created',
        ),
    ]
