# Generated by Django 4.1.2 on 2022-10-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0007_remove_user_email_user_github_user_host_user_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profileImage',
            field=models.URLField(default='https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png', max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='382803a18fd9df159675bc8a5a950878a86c46fe72c6a95712920685f9af122c', max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='url',
            field=models.CharField(default='http://127.0.0.1:8000/authors/382803a18fd9df159675bc8a5a950878a86c46fe72c6a95712920685f9af122c', max_length=255),
        ),
    ]
