# Generated by Django 4.1.2 on 2022-10-23 03:09

import api.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0008_user_profileimage_alter_user_id_alter_user_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=api.user.models.generate_id, max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
