# Generated by Django 4.1.2 on 2022-10-27 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0008_alter_followers_follower_alter_followers_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followers',
            name='user',
        ),
        migrations.AddField(
            model_name='followers',
            name='followed_user',
            field=models.CharField(default='followed_user', max_length=200),
        ),
        migrations.AlterField(
            model_name='followers',
            name='follower',
            field=models.CharField(default='follower', max_length=200),
        ),
    ]
