# Generated by Django 4.1.2 on 2022-10-27 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0010_alter_followers_followed_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='followed_user',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='followers',
            name='follower',
            field=models.CharField(default='', max_length=255),
        ),
    ]
