# Generated by Django 4.1.2 on 2022-11-15 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default='asdf', on_delete=django.db.models.deletion.CASCADE, related_name='comment_post', to='api.post', verbose_name='Post'),
            preserve_default=False,
        ),
    ]
