# Generated by Django 4.1.2 on 2022-11-15 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(default='text/plain', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(default='PUBLIC', max_length=50),
        ),
    ]
