# Generated by Django 4.1.2 on 2022-11-21 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_like_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='created',
        ),
    ]
