# Generated by Django 4.1.2 on 2022-10-31 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_inbox_followrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='inbox',
            field=models.ManyToManyField(to='api.post'),
        ),
    ]
