# Generated by Django 4.1.2 on 2022-10-31 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_inbox_inbox'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inbox',
            old_name='inbox',
            new_name='Posts',
        ),
    ]
