# Generated by Django 4.1.2 on 2022-10-31 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_inbox_inbox_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbox',
            name='type',
        ),
    ]
