# Generated by Django 4.1.2 on 2022-10-31 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_inbox_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbox',
            name='Posts',
        ),
        migrations.AddField(
            model_name='post',
            name='inbox',
            field=models.ManyToManyField(to='api.inbox'),
        ),
    ]
